### ISSUE TITLE
sys_signalmap addon is missing in releases

### ISSUE THREAD

**Issue by Sniperhid** [IDI-Systems/acre2#998] opened 2020-07-25 13:47 UTC
**Description:**
Essentially `acre_sys_signalmap.pbo` has been missing in the last two releases: 2.7.4 and 2.7.3.

**Steps to reproduce:**
- Download 2.7.4 or 2.7.3 release on github
- Note `acre_sys_signalmap.pbo` is missing compared to 2.7.2 or prior where it is present.

**Expected behavior:**
 `acre_sys_signalmap.pbo` should be present

This is quite peculiar as it shows in source control and should be present if built locally.

**Comment by jonpas** [comment] 2020-08-04 20:36
Later dev-builds have it, looks like it was a problem with the environment. Confirmed fixed with release builds on current setup.

**Closed as completed by jonpas** 2020-08-04 20:36 UTC
Labels: bug
