### ISSUE TITLE
ACRE2 Unmuting TS3 Mic Every ~3 Seconds

### ISSUE THREAD

**Issue by Quailsnap** [IDI-Systems/acre2#654] opened 2019-03-30 03:36 UTC
I think this is a feature, not a bug, but just to make sure --

Is ACRE2 supposed to force client mic unmute at a regular interval? Neither push-to-mute, nor toggle-mute works, and I would prefer to be able to push-to-mute when I cough into my mic or want to talk to a livestream.

**Comment by TheMagnetar** [comment] 2019-05-05 09:26
This is by design. If muting is required, there is the PTT option in TeamSpeak. Closing.

**Closed as completed by TheMagnetar** 2019-05-05 09:26 UTC
Labels: by design
