### ISSUE TITLE
ACRE.dll crash on mission start

### ISSUE THREAD

**Issue by milivojm** [IDI-Systems/acre2#221] opened 2017-02-19 12:16 UTC
**Arma 3 Version:** `1.66.139.586` (stable)
**CBA Version:** `3.1.2` (stable)
**ACRE2 Version:** `2.3.0.926` (stable)

**Mods:**
@ace
@acex
@acre2
@ares
@asr_ai3
@cba_a3
@chestpack
@cnto_additions
@cnto_assets
@cnto_units
@cup_terrains
@fallujah
@fata
@fdf_podagorsk
@ffcamopack
@imrali
@lingor_a3
@mbg_killhouses_a3
@niarms
@nimitz
@panthera
@prkz
@project_opfor
@rds
@rds_civ
@rds_rhs_comp
@rh_acc
@rhs_afrf3
@rhs_gref3
@rhs_usf3
@st_ui
@tao_foldmap_a3
@tf47_launchers
@thirsk
@rhs_saf3
@balc

**Description:**

Arma 3 crashes with event viewer log entry:

```
Faulting application name: arma3.exe, version: 1.66.139.586, time stamp: 0x5847dbb3
Faulting module name: acre.dll, version: 0.0.0.0, time stamp: 0x58443f4b
Exception code: 0xc0000409
Fault offset: 0x000ec528
Faulting process id: 0xf74
Faulting application start time: 0x01d28a9ea796fa38
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Arma 3\arma3.exe
Faulting module path: C:\cnto\@acre2\acre.dll
Report Id: f22d082e-3d06-40e9-8769-e360b1bb60e5
Faulting package full name: 
Faulting package-relative application ID: 
```

**Steps to reproduce:**
1. I was working in Eden editor, clicked preview.
2. Game showed up ok and I clicked return to Eden.
3. Done some changes and clicked preview again.
4. Game crashes with event viewer log entry (above)

It happens once in two mission preview runs. And sometimes while playing multiplayer mission on dedicated server.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**Placed Modules:**
Basic Mission Setup

**RPT log file:**
https://1drv.ms/u/s!AqgVT4o86VaQlH9K8Qdt3bbFdlQt

Acre log
https://1drv.ms/u/s!AqgVT4o86VaQlQBSnWfhK78kNMIA

TS Version 3.0.19.4

**Comment by TheMagnetar** [comment] 2017-02-19 12:59
Can this be reproduced with CBA and ACRE alone (or even with ACE3)? Also, the latest stable version is 2.4.0.942 and it requires TS version greater than 3.1

**Comment by Sniperhid** [comment] 2017-02-19 13:34
Some questions that would help further:
- Does this issue happen with every island (map)?
- Do you use Tobii EyeX?
- As @TheMagnetar said does this occur if it is just CBA+ACRE2 running? (In which case finding out which mod combination sets it off would be useful).

**Comment by Sniperhid** [comment] 2017-02-20 10:20
`2017-02-19 12:46:19,241-{ERROR}- WRP Parsing exception: bad allocation` - Just noticed this in the acre_dll.log. This seems to match the timestamp in the RPT. This would seem to indicate that ACRE is unable to allocate some necessary memory. Out of curiosity how much RAM does your system have?

**Comment by milivojm** [comment] 2017-02-20 11:22
Hey guys. I will try and reproduce the issue without other mods and ring you back.

- I have noticed that issue on Altis
- I don't use Tobii EyeX
- My system has 8 GB RAM

**Comment by milivojm** [comment] 2017-02-20 16:39
I can confirm that CBA and ACRE alone with basic mission setup module did not reproduce the issue. 

I'm out of ideas now as, unfortunately, the mission preview with large modset crashes the game with the above error message every 2 launches. It smells on memory leak in arma3.exe (somewhere) and I suspect it breaks in acre.dll due to "out of memory" problem when acre maybe wants to malloc memory for something. 

Is there anything you can do guys to help me out? Does the exception code and fault offset mean anything to you?

I have been tracking this issue for over two weeks with no luck.

**Comment by Sniperhid** [comment] 2017-02-20 16:47
My gut feeling is that the large modpack is probably running Arma 3 towards its maximum allowed memory. Have you got a second screen to monitor how much RAM it is utilising? The maximum memory A3 can use has changed a bit between patchs you can set a max using the game startup parameter `-maxMem=3071` - This may help
https://community.bistudio.com/wiki/Arma_3_Startup_Parameters

64bit Arma 3 should be coming with the next stable patch will may also help as it will also raise the limits higher.

It may not not be a max memory issue but it seems like a good place to start!

**Comment by milivojm** [comment] 2017-02-20 17:05
It was definitely around that maximum judging by the procdump memory dump file size. Maybe I should limit the memory to lower value and prevent it to go there at all, something like 2GB?

**Comment by TheMagnetar** [comment] 2017-02-20 17:21
I know it is not a workaround but what about trying the 64bit executables?

**Comment by ares** [comment] 2017-02-20 18:52
Guys, could update your issue template so the mod list does not mention github users? Just wrap it into backticks or something? Thanks :-)

**Comment by jonpas** [comment] 2017-02-20 18:56
@ares it is, as seen [here](https://github.com/IDI-Systems/acre2/blob/master/.github/ISSUE_TEMPLATE.md). We can't stop people from removing the backticks though. ¯\\\_(ツ)_/¯

I'll change it to be a code block rather than each line separately though.

**Comment by milivojm** [comment] 2017-02-21 22:45
I've set `-maxMem=2047` and the problem now occurs a lot later with the complete modpack. Though why in the end it shows acre.dll I don't know.

**Comment by jonpas** [comment] 2017-02-21 22:57
As far as I know changing `-maxMem` can lead into issues, that's why it's not as high by default. However since you are still getting crashes, it seems either too many mods for Arma to handle or some other mod causing issues. Would be pretty hard to find though, but if you could that would be interesting to see (would mean checking different combinations or single mods... etc).

**Comment by ares** [comment] 2017-02-23 14:34
Thank you @jonpas

**Comment by jonpas** [comment] 2017-03-18 13:19
I am going to close this issue, as it seems entirely memory related, more apparent on 32-bit Arma. If this still happens and ACRE2 seems to be the problem, reopen the issue.

**Closed as completed by jonpas** 2017-03-18 13:19 UTC
Labels: can't reproduce, need more info
