### ISSUE TITLE
AN/PRC 152 Range too far

### ISSUE THREAD

**Issue by DuffMan343** [IDI-Systems/acre2#876] opened 2019-12-31 20:55 UTC
Arma 3: 1.96
CBA: 3.12.2
ACRE2: 2.7.2.1022
CUP Terrains

Description:
The AN/PRC in my personal testing has far too long of a range. On Chernarus winter, we were reading each other 5x5 from roughly 12k (see photo below, CTAB info and DEBUG reading 83% clear). The 343 cuts out as expected, as well as the 117.
![20191231153247_1](https://user-images.githubusercontent.com/59400289/71634024-59f62f00-2be6-11ea-9f65-f973adcf23c0.jpg)

Steps to reproduce:
Langley-Rice
Full duplex
All other settings standard
All vanilla / CUP maps + Lythium

Expected behavior:

The AN/PRC can be recieved 5x5 from up to and including 13k.
Where did the issue occur?

Occurs in temporary MP server
Log Files:

This issue does not generate any error messages in the .rpt, and it does not cause any script error pop-up messages either.
Additional context:

We are very new to ACRE, so any mistakes made on our end may be very basic. Any advice much appreciated.

**Comment by DuffMan343** [comment] 2020-02-03 03:59
Yep. Rgr that, TFAR it is.

**Comment by Drofseh** [comment] 2020-02-03 10:14
Duplicate of #827

**Comment by jonpas** [comment] 2020-04-15 18:24
As stated in other issues, you may use LOS Simple for now. Issues are now linked, keeping it all in one.

> Yep. Rgr that, TFAR it is.

That is your choice, we cannot provide immediate support.

**Closed as completed** 2020-04-15 18:23 UTC
Labels: bug, duplicate
