### ISSUE TITLE
ACRE2 is Incompatible with the Latest version of Teamspeak

### ISSUE THREAD

**Issue by Traviiiii** [IDI-Systems/acre2#1251] opened 2023-06-14 18:56 UTC
**Description:**
Following the latest Teamspeak update ([3.6.0](https://community.teamspeak.com/t/teamspeak-3-client-3-6-0/41112)), the TS plugin fails to load due to the API version in the plugin not being compatible with the new TS version. 

**Screenshots:**
![image](https://github.com/IDI-Systems/acre2/assets/66571512/78c6761b-e1f7-4cc5-8cab-8882ab649da3)

**Comment by jonpas** [comment] 2023-06-14 19:33
Duplicate of #1247.

**Closed as completed by jonpas** 2023-06-14 19:33 UTC
Labels: duplicate
