### ISSUE TITLE
ACRE2 does not work when using continous transmission or setting voice activation too low.

### ISSUE THREAD

**Issue by StoneLabs** [IDI-Systems/acre2#1008] opened 2020-08-10 18:24 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98.146373 (stable) (latest)`
- **CBA:** `3.15.1.200418 (latest)`
- **ACRE2:** `2.7.4.1027 (workshop) (latest)`

Though that issue has been there for as long as I have used ACRE2.

- [X] Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!

**Description:**
Acre will not work if TeamSpeak is configured in a way where the microphone is constantly active.

**Steps to reproduce:**
1. Open TeamSpeak
2. Go to settings -> Capture
3. Either turn on continuous Transmission or move voice detection to -50
4. Host a new game with at least another player
5. Try talking with acre ingame

**Workaround:**
- Turn of continuous Transmission
- Make sure microphone is not active when you're not talking. (Blue light goes off from time to time)

**Note:**
This really isn't that big of a problem. Most people dont use continous transmission and turning it off fixes the problem. But I haven't found it in the issue tracker so I thought I might as well throw it in here.

**Comment by NouberNou** [comment] 2020-08-10 18:43
I am not exactly sure how this is ACRE related... This is just a general TS thing. If TS is always transmitting then there is no PTT events.

I mean I guess its good to log this as a potential issue, but I'd hesitate to call it a bug.

I'll close this out I guess as working as intended but to be aware of it?

**Closed as completed by NouberNou** 2020-08-10 18:43 UTC
Labels: bug, wontfix, TeamSpeak's fault

**Comment by StoneLabs** [comment] 2020-08-10 19:21
I guess you could say the fact that acre can't function without PTT events is a problem on acre's side.
Anyways, it took me I while to figure it out when I first used acre. So maybe someone will stumble across this and save themselves some headaches.

**Comment by LordKobra** [comment] 2024-10-07 22:24
I still run into this issue mid-game, when using voice detection, but not even set to -50. It works and then stops working. Going full push-to-talk seems a little overkill for near communication, so do you perhaps know how sensitive TS3 is for these events. Why does voice detection work and then stop working? Shouldn't more people run into this issue?
