### ISSUE TITLE
AN/PRC-117F radio does not fit in vanilla (Contact) radio backpacks

### ISSUE THREAD

**Issue by Ionaru** [IDI-Systems/acre2#976] opened 2020-06-07 23:47 UTC
**Is your enhancement related to a problem?**
The AN/PRC-117F radio does not fit inside the vanilla radio backpacks added in the Contact DLC like `B_RadioBag_01_black_F`

**Solution you'd like:**
Make the AN/PRC-117F radio slightly smaller so it fits inside these new vanilla radio backpacks.

**Alternatives you've considered:**
Modify the vanilla backpacks to be bigger, but this might conflict with other mods.

**Additional context:**
![image](https://user-images.githubusercontent.com/3472373/83982790-aaa64c80-a929-11ea-8588-ec5fd49b6fbf.png)

**Comment by jonpas** [comment] 2020-06-08 09:55
Duplicate of https://github.com/IDI-Systems/acre2/issues/854.

We would accept a PR providing optional compatibility by adjusting size of the backpacks. Not reducing the size of the radio though.

However you can easily do that yourself anyways: https://github.com/IDI-Systems/acre2/issues/854#issuecomment-543489897

**Comment by jonpas** [comment] 2023-09-14 01:24
See https://github.com/IDI-Systems/acre2/pull/1261#issuecomment-1642108059.

**Closed as not planned by jonpas** 2023-09-14 01:24 UTC
Labels: duplicate
