### ISSUE TITLE
Radio Boosters

### ISSUE THREAD

**Issue by godgutten** [IDI-Systems/acre2#969] opened 2020-05-24 01:24 UTC
**Is your feature request related to a problem?**
No

**Solution you'd like:**
An item or and object that can be placed to boost radio signals like in TFRA. This would be nice so we can place down radio towers or radio positions to boost our radios specially for long range etc.

**Alternatives you've considered:**
Or add a code that we can add to a object in Eden editor and change how much to boost etc

**Additional context:**
Have none

**Comment by jonpas** [comment] 2020-05-24 04:55
Uhm, GSA?

**Comment by godgutten** [comment] 2020-09-14 16:32
But like one that you can place down and walk 100 meters away from but it is still connected

Say you are on one side of one mountain and someone else is on the other side of the mountain If it then can be sent via a radio booster that is on top of the mountains.

Also no need to be a dick @jonpas

**Comment by NouberNou** [comment] 2020-09-14 16:35
That'd be retrans, which we haven't really looked into doing in ACRE2 for a number of reason (though was in ACRE for Arma 2).

You can't simply boost a radio signal (I mean you could fake it, but ACRE is generally against faking it, at least at the fundamental physical level).

**Comment by jonpas** [comment] 2020-09-14 19:18
GSA is a viable alternative, no clue what makes you think I was trying to be a dick or whatever. But your thoughts are your own, leave some of them private.

What @NouberNou said, retrans would be great, but it is also a lot of work. GSAs are halfway solution in terms of gameplay.

**Comment by jonpas** [comment] 2023-09-14 01:14
Essentially duplicate of #381.

**Closed as not planned by jonpas** 2023-09-14 01:14 UTC
Labels: duplicate, feature request
