### ISSUE TITLE
152 not working on dedicated servers at all

### ISSUE THREAD

**Issue by MadSoloSniper** [IDI-Systems/acre2#684] opened 2019-05-23 14:03 UTC
**Arma 3 Version:** `1.92.145639` (stable / rc / dev)
**CBA Version:** `3.11.2.190515` (stable / dev + commit hash)
**ACRE2 Version:** `2.6.3.103` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- Acre2
- alive
- full spread of CUP
- CFP
- ACEX
and some maps (should not be the issue so not listed)

**Description:**
- Dedicated hard iron server.  Works fire. No errors. 152s do not transmit or receive, though the player sees that it's keying up.  343 and 117 work fine. We haven't tested the others extensively.

**Steps to reproduce:**
- I can have you join our server and it happens every time.

**Where did the issue occur?**
- Dedicated hard iron box (not a blade or shared) at a data center in KC USA

**Placed Modules:**
- None

**RPT log file:**
- None - or you'll have to direct me

**Comment by TheMagnetar** [comment] 2019-05-23 22:37
We really need to get those RPTs because we cannot reproduce it on our end.

If you can, provide yours that can be found under "C:\Users\XXXX\AppData\Local\Arma 3" would be of great help. However, most of the reports that say "x radio is not working" are usually caused by assigning Radios with IDs (acre_prc152_id_1 for example) to the player's gear through the Arsenal. ACRE radios must always be given without IDs (`player addItem "acre_prc152"`)

**Comment by TheMagnetar** [comment] 2019-05-25 14:23
Anything new?

**Comment by MadSoloSniper** [comment] 2019-06-05 00:21
Sorry, was traveling.  Will look for reports and also test again tonight (June 4, 2019).  Current issue 343 works across the map but will get sketchy when within 100M of another player.  Looking for reports and will post here if I can find.  Thanks,

**Comment by TheMagnetar** [comment] 2019-06-05 04:32
That is normal with a 343

**Comment by TheMagnetar** [comment] 2019-06-14 15:22
Closing the issue. If this happens again, please feel free to reopen.

**Closed as completed by TheMagnetar** 2019-06-14 15:22 UTC
Labels: can't reproduce, need more info
