### ISSUE TITLE
343 radio range is over 500m 

### ISSUE THREAD

**Issue by McFurSun** [IDI-Systems/acre2#763] opened 2019-08-06 11:08 UTC
**Arma 3 Version:** 1.94.145903 (stable)
**CBA Version:** 3.12.0.190708 (stable)
**ACRE2 Version:** 2.7.0.1010 (stable)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- When using the 343 radio it has a longer than expected range. The acre documentation states 500m (850 in perfect conditions), in testing we have identified it starts to cut out at around 1.9 km.

Tested on Tanoa and Altis maps.
![20190806222127_1](https://user-images.githubusercontent.com/19367167/62533459-d59fba00-b89a-11e9-894b-3f49423028b9.jpg)
![20190806215144_1](https://user-images.githubusercontent.com/19367167/62533470-dc2e3180-b89a-11e9-904e-dfe3a8b6202f.jpg)

**Steps to reproduce:**
- Use 343 radio beyond the range that it is expected to cut out.

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**RPT log file:**
- Server RPT https://pastebin.com/iDmHqC7V
- Server ext log https://pastebin.com/8dBaUnYY
- Client RPT https://pastebin.com/2gk4ARD4
- Client ext log https://pastebin.com/Hk8hRn4n

**Comment by Kanthier** [comment] 2019-08-06 23:24
Not the mod author, but I will say that "Ideal conditions" are considered line-of-sight on flat terrain (e.g. salt flats). IRL radio interference comes in two forms - constructive and destructive. Destructive is just how it sounds - it  'destroys' signal strength and reduces radio range. Constructive does the opposite; it reinforces signal strength and extends range beyond what "ideal" conditions would normally allow

afaik ACRE models both types of interference, so might it be that? I haven't used the 343 since my group were initially testing out which radios would work best for our setup (and at the time 343s were slightly buggy) so it might well a longer-than-intended range instead.

**Comment by jonpas** [comment] 2019-08-06 23:35
Is this with default terrain loss of 0.5? Can you try with 1.0?

Also, did this start happening only with recent updates? Can you try a 2.6.x build of ACRE2?

**Comment by McFurSun** [comment] 2019-08-06 23:44
Yes was using 0.5.
Can try with 1.0 but will be in 7 hrs time before I can post results.

Yes, only noticed it with 2.7 build.
Will revert the server and test a mission using 2.6 build tonight.

**Comment by TheMagnetar** [comment] 2019-08-07 17:40
In addition, try to solve the following issues that may be caused by your gear script or by using Virtual Arsenal to equip radios in 3DEN.

```
19:08:07 [ACRE] (sys_server) WARNING: Duplicate radio ID found! Attempting replace of (Mikoiacre_prc343_id_2) idi\acre\addons\sys_server\fnc_masterIdTracker.sqf:198
19:08:08 [ACRE] (sys_server) WARNING: Duplicate radio ID found! Attempting replace of (Mikoiacre_prc152_id_2) idi\acre\addons\sys_server\fnc_masterIdTracker.sqf:198
19:08:08 [ACRE] (sys_server) WARNING: Id object relation created independently of unique ID creation process (acre_prc343_id_3)! idi\acre\addons\sys_server\fnc_masterIdTracker.sqf:252
19:08:08 [ACRE] (sys_server) WARNING: Id object relation created independently of unique ID creation process (acre_prc152_id_3)! idi\acre\addons\sys_server\fnc_masterIdTracker.sqf:252
```

Something is wonky in there

**Comment by McFurSun** [comment] 2019-08-07 19:13
Ok. The server RPT covers all 3 missions we tried that night.
That script would be for the 1st mission. The next two were using just cba and acre in the command line and the missions were 6 player slots with a zeus module for each. 
Made them really basic and didn't add anything else to ensure it wasn't something we had introduced that caused the bug. 

Also attempted to test with terrain loss set to 1.0 and confirming that 2.6.x didn't have the bug but couldn't get another person on to assist. Will try again tonight, NZST.

**Comment by McFurSun** [comment] 2019-08-08 09:52
In the picture below was the distance we started to break up using Acre ver 2.6.4.1006
positions marked as mcfur and 2nd update
Still seems excessive for a 343, but we never noticed it back then.

Have you been able to reproduce this? Or is it something only we have experienced? If the latter then I'll look at options on our end instead of pursuing this issue.

![20190808214222_1](https://user-images.githubusercontent.com/19367167/62693131-fea08600-ba25-11e9-899e-eedaed1fc924.jpg)

**Comment by TheMagnetar** [comment] 2019-08-11 17:42
Same as #765. I have done some testing on my end and I get the expected results. Can you please check the following settings?

- Propagation mode: LOS Multipath
- Terrain Loss Coefficient at least at 0.9
- Execute the following command in the  console: acre_sys_signal_showSignalHint = true

Report your findings with different propagation modes.

**Comment by TheMagnetar** [comment] 2019-08-12 21:42
Radio ranges are OK. Closing. Feel free to reopen it if you deem it necessary!

**Closed as completed by TheMagnetar** 2019-08-12 21:42 UTC
Labels: can't reproduce, need more info
