### ISSUE TITLE
ACRE2 needs API Update - not working on stable TS3 v3.6.0

### ISSUE THREAD

**Issue by pablogsalto** [IDI-Systems/acre2#1252] opened 2023-06-14 23:43 UTC
ACRE2 is not working anymore on new TS version, it needs an API update, 

Screenshot of TS3
![image](https://github.com/IDI-Systems/acre2/assets/49418289/e16ad117-5b71-448d-ba63-37a3177aa2c5)

In turn, on the Ts3 website users report that no plugin is working, from Ts3 they respond that it is the plugin authors who must update the APIs
![image](https://github.com/IDI-Systems/acre2/assets/49418289/bc78582d-fcdf-4ea3-a640-a994555b6bd9)

Best regards 
Taskforce Foxtrot - ArmA III Community

**Comment by jonpas** [comment] 2023-06-14 23:46
Duplicate of #1247.

**Closed as completed by jonpas** 2023-06-14 23:46 UTC
Labels: duplicate
