### ISSUE TITLE
ArmA 3 stopped working after setting up frequenzy on 117

### ISSUE THREAD

**Issue by Frostie2811** [IDI-Systems/acre2#234] opened 2017-02-24 09:44 UTC
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.x.x` (stable)
**ACRE2 Version:** `2.4.0` (stable)

**Mods:**
```
- @CBA_A3
- @acre2
- @ACE3 3.8.3
```

**Description:**
After i configured my frequenzy on the 117 my game is crashing every time. Just Saying ArmA3 stopped working. This only occures on a dedicated server. When i hosting a server myself and setting the frequency up ArmA3 doesnt crash.

**Steps to reproduce:**
- Picking up the 117
- setting up the frequenzy
- few settings after that arma is crashing

**Where did the issue occur?**
- Dedicated (occur) / Self-Hosted Multiplayer (didnt occur)

**Placed Modules:**
- ACRE Modules and ACE3 Modules

**RPT log file:**
-  acre_dll.log : http://pastebin.com/GGFvw8c0

RPT: https://www.dropbox.com/s/n9mwi5qe8jgm27k/arma3_2017-02-23_21-33-10.rpt?dl=0

RPT2: https://www.dropbox.com/s/gvfzv5l1i5jsto2/arma3_2017-02-23_19-28-40.rpt?dl=0

**Comment by TheMagnetar** [comment] 2017-02-24 10:48
The provided RPTs have additional mods loaded as opposed to your description. Can you try to reproduce it without additional mods? Placing only modules does not help since mods are loaded anyway. Nevertheless I will look into the issue

**Comment by Frostie2811** [comment] 2017-02-24 22:38
Yeah i think it isnt the problem with ACRE. It was just a guess because it only occurred to me since I used ACRE. But today it crashed also at some others point when i didnt use the radios. i think there just something wrong with my arma since a few days :(

**Comment by jonpas** [comment] 2017-02-26 13:05
There is a bunch of these just before the crash. But those are known and shouldn't cause a crash (at least haven't yet). It does happen in both cases though.
```
21:43:12 Extreme texture size (1x1)
21:43:12 Texture init failed.
```

**Comment by Frostie2811** [comment] 2017-02-26 15:04
Well i only can say that this happens everytime when im done with setting the frequenzy up with the 117, 5-10 secs after im done with setting it up an i'm in the main menu of the 117 arma is crashing. But why i really dont know.

I tried it with a few mates from my clan and I am the only one with that problem.

I really dont think that my Components of my PC are to weak for A3

i7-6700K
16GB Ram
ArmA3 is running on a 128GB M2 SSD
MSI Nvidia GeForce 970 GTX

**Comment by jonpas** [comment] 2017-02-26 15:38
I will try to reproduce this on our dedicated server.

**Comment by jonpas** [comment] 2017-02-26 18:26
I couldn't reproduce. Could you take screenshots of the steps you took?

**Comment by Frostie2811** [comment] 2017-02-26 19:44
yeah i will take them tommorow morning ^^

**Comment by Frostie2811** [comment] 2017-02-27 13:30
So i took some Screenshots few minutes ago on our dedicated server.
Step 1: Opening the 117 http://i.imgur.com/uOcJ2jX.jpg
Step 2: Moving to the Menu http://i.imgur.com/Dekq4Bp.jpg
Step 3: Opening the Freq and Setting it up http://i.imgur.com/RImywRk.jpg , http://i.imgur.com/XHyExnY.jpg
Step 4: Back in the Menu http://i.imgur.com/Dekq4Bp.jpg 
Step 5 My ArmA is crashing 5 Seconds Later

**Comment by jonpas** [comment] 2017-02-27 13:50
I see you have a comma in there instead of the dot, like in #235. Did you try this with latest CBA? And make sure your preset radio channel scripts are correct as well if you are using them (try without one first to confirm).

**Comment by Frostie2811** [comment] 2017-02-27 15:59
Just Tried it with the latest CBA, its still happening, checked my ram also while im setting the radio up 1700 MB where just used at this moment by ArmA3. The thing is i'm the only one with this problem at my unit.

**Comment by jonpas** [comment] 2017-02-27 16:03
What language are you playing the game with?

**Comment by Frostie2811** [comment] 2017-02-27 16:03
German

newest RPT https://jpst.it/Unn9

**Comment by jonpas** [comment] 2017-02-27 16:25
Switched to German, worked fine, there is no comma either, just a dot that can't be edited (your comma apparently can since its marked).

**Comment by Frostie2811** [comment] 2017-02-27 16:50
Yeah the test with the screenshot was with the older CBA Version where i had the comma, tried it with the newest CBA version after you mentioned it. I also have the dot know but still the crashing problem. Like i said earlier im the only one with this problem at my unit so i think now thats a problem somewhere with my PC.

**Comment by Soldia1138** [comment] 2017-02-27 16:56
Out of curiosity: This is only happening if programming the 117? Not 152? Because both share the operating system and therefore acre code >99%

**Comment by Frostie2811** [comment] 2017-02-27 17:09
Didnt tried the 152 till now because we dont use it. But after you mentioned it i tried it immediatly and yeah i have the same problem with the 152 too.

**Comment by Frostie2811** [comment] 2017-03-03 09:55
Well tested it today after i made a fresh install of windows and everything else. I dont have this problem anymore. And because i was the only person with that problem i think it solved then ^^

**Comment by TheMagnetar** [comment] 2017-03-03 13:09
Good to know it is solved! Closing.

**Closed as completed by TheMagnetar** 2017-03-03 13:09 UTC
Labels: can't reproduce, need more info
