### ISSUE TITLE
TS 3.2 + ACRE 2 randomly crash both TS and Arma 3

### ISSUE THREAD

**Issue by grappas** [IDI-Systems/acre2#568] opened 2018-08-14 15:06 UTC
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACRE2 Version:** `2.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
- TS 3.2 + newest ACRE 2 from SW crashes both Teamspeak and Arma 3.

**Steps to reproduce:**
- From description. It's pretty hard to reproduce. It happening kinda randomly (when you use radio speak  button (CL by default)).

**Where did the issue occur?**
- Dedicated multiplayer (as client).

**Placed Modules:**
- N/A

**RPT log file:**
- hard to reproduce

**Comment by Soldia1138** [comment] 2018-08-14 16:09
This is related to #567. 

It is highly recommended not to upgrade. Issue occurs with both TFAR and ACRE so it is likely something on TS side. 

We will try to gather more information and report it here.

**Comment by dedmen** [comment] 2018-08-15 06:58
Ref to TFAR https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1437

**Comment by Tennessee-Timmy** [comment] 2018-08-15 19:27
I logged out of admin and it crashed, probably just a coincidence 'tho.

**Comment by jonpas** [comment] 2018-08-17 15:54
Ref: https://twitter.com/dedmenmiller/status/1030354473124868097

Closing this one as duplicate of #567 as that one has more information (logs and such).

**Closed as completed** 2018-08-17 15:55 UTC
Labels: duplicate
