### ISSUE TITLE
Dead players on the "MenuPosition" respawn screen are unable to communicate with other dead players

### ISSUE THREAD

**Issue by Superxpdude** [IDI-Systems/acre2#916] opened 2020-04-15 17:09 UTC
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98.146303 Stable`
- **CBA:** `3.15.0.200404 Stable (Workshop)`
- **ACE3:** `3.13.1.46 Stable (Workshop)`
- **ACRE2:** `2.7.2.1022 Stable (Workshop)`
_Make sure to reproduce the issue with only CBA, ACRE2 (and optionally ACE3) on a newly created mission!_

**Description:**
Dead players with both the "MenuPosition" and "Spectator" respawn templates are unable to communicate with other dead players when at the "MenuPosition" screen. Communication is only possible when at the "Spectator" view within the "MenuPosition" screen.

**Steps to reproduce:**
***Method 1***
- Create a mission with the "MenuPosition" and "Spectator" respawn templates.
- Play the mission
- Die
- Enter `[] call acre_api_fnc_isSpectator` into the a watch field in the debug console. Note that it will return `false`
- Press the "Spectator" button
- Note that `[] call acre_api_fnc_isSpectator` returns `true`
- Switch out of the spectator view (i.e. to select a respawn position)
- Note that `[] call acre_api_fnc_isSpectator` once again returns `false`

**Method 2**
- Create a mission with the "MenuPosition" and "Spectator" respawn templates.
- Play the mission with others
- Have you and one other person die
- Note that you will still hear the voices of those around your body, but you are unable to speak (because you are dead).
- Note that you cannot communicate with other dead players unless you have both pressed the "Spectator" button on the "MenuPosition" screen.

**Expected behavior:**
Dead players should be switched to ACRE Spectator (or something similar) so that they can communicate with other dead players. Their "position" (for hearing alive players) should be on their body unless they have a spectator camera active.

**Where did the issue occur?**
- Dedicated, Editor (Multiplayer)

**Log Files:**
- https://gist.github.com/Superxpdude/4aa6b343ec8c4e2f0147b0a9a3bf75b7

**Additional context:**
As far as I can tell ACRE2 uses an event that fires when the spectator camera is opened or closed to automatically switch the player to ACRE Spectator. It looks like this fires when the "MenuPosition" spectator is opened or closed as well.

**Screenshots:**
N/A

**Comment by jonpas** [comment] 2020-04-15 18:07
We only use default EG Spectator (vanilla) to toggle spectator.

I personally don't evne know what "MenuPosition" is, but unless there is a separate event for this, we can't really handle it gracefully.

**Comment by Soldia1138** [comment] 2020-04-16 13:20
@Superxpdude But isn't that the expected behavior? The MenuPosition Respawn is in fact a Respawn.

If we'd add the ability to communicate in that status that would be always the case (e.g. if one uses the MenuPosition purely for Respawing then it would be possible to hear everything like a spectator).

Just see the risk of breaking things here.

**Comment by jonpas** [comment] 2020-04-16 13:37
We would effectively allow people who "can respawn" and "can NOT spectate" to talk with spectators. This would break intended mission functionality as you could talk to spectators when you are not supposed to (eg. people out of respawns and forced to spectator being able to talk to those who have respawn available, when they shouldn't).

Closing this, if you have other input or think that is incorrect, we'll reopen.

**Comment by Superxpdude** [comment] 2020-04-16 20:54
@jonpas "MenuPosition" is the built-in respawn template that allows someone to select which respawn position they would like to use (by looking at a map).

@Soldia1138 the issue comes up when players are able to access *both* the "MenuPosition" and "Spectator" views. I would think they would be able to communicate as a spectator when dead in this case. For my particular use, this is a semi-common state for mission design. Existing attempts to work around this have been pretty hacky, since the player effectively ends up switching out, and then back into ACRE spectator when they close the "MenuPosition" spectator view.

As far as I can tell, ACRE hooks into the `DisplayLoad` and `DisplayUnload` CBA event handlers for the `RscDisplayEGSpectator` class in order to move the player in and out of spectator status. From my testing, this fires both when the full "Spectator" is opened, as well as when the minimal spectator within the "MenuPosition" screen is opened.

There are however, two variables that could be used to identify if "MenuPosition" is being used as well, in order to either:
- Ensure that the player is set as spectator when dead if they have *both* the "MenuPosition" and "Spectator" options, or
- Prevent the player from being automatically moved if they open the spectator view within "MenuPosition".

The two values are as follows:
`missionNamespace getVariable "BIS_RscRespawnControlsMap_shown"` returns `true` if the *map* is shown in the "MenuPosition" respawn menu.
`missionNamespace getVariable "BIS_RscRespawnControlsSpectate_shown"` returns "true" if the *spectator* is shown in the "MenuPosition" respawn menu.
Both of these values return `false` if "MenuPosition" is not active, or `nil` if "MenuPosition" is not used in the current mission.

If needed, I could try to put together a pull request that would modify [fnc_spectatorEGDisplayLoad.sqf](https://github.com/IDI-Systems/acre2/blob/master/addons/sys_core/fnc_spectatorEGDisplayLoad.sqf), and [fnc_spectatorEGDisplayUnload.sqf](https://github.com/IDI-Systems/acre2/blob/master/addons/sys_core/fnc_spectatorEGDisplayUnload.sqf) to accomplish one of the following:
- Only fire if the two previously mentioned variables are `false` or `nil` so that players would not be switched in and out of spectator while still dead, or
- Create a new CBA setting that controls if players are automatically switched in and out of spectator (to be set on the mission or server level, would default to "enabled"), and reference that value in these functions. This would allow missions (or servers) to handle the spectator switching manually. This is probably the safer option, since it would allow for increased flexibility in mission design, without having any effect on existing missions.

**Comment by jonpas** [comment] 2020-04-16 21:49
> Only fire if the two previously mentioned variables are false or nil so that players would not be switched in and out of spectator while still dead, or

I think this is a reasonable solution. If you are able, please do open a PR. None of us use this system.

**Comment by Superxpdude** [comment] 2020-04-17 17:12
@jonpas I have submitted pull request #929 with the mentioned fix.

There is no change for anyone that is not using "MenuPosition" for respawn since both of the referenced variables should be undefined.
For missions using respawn, this will prevent players from being toggled in and out of ACRE spectator as they switch between the MenuPosition map, and MenuPosition spectator.

**Comment by jonpas** [comment] 2020-05-14 13:54
Closed by #929

**Closed as completed by jonpas** 2020-05-14 13:54 UTC
Labels: enhancement
