### ISSUE TITLE
Add megaphone feature

### ISSUE THREAD

**Issue by hbeni** [IDI-Systems/acre2#1235] opened 2023-03-24 09:41 UTC
Hi there,
some time ago we played some police missions. For advanced crowd control missions, it would be nice to have some "megaphone" radio item that basicly behaves like direct speech, but with more range and an appropriate sound effect, and, if possible, more directed (so the amplification only works in some kind of sound cone in the viewed direction).

**Comment by jonpas** [comment] 2023-09-14 01:31
Duplicate of #970.

**Closed as not planned by jonpas** 2023-09-14 01:31 UTC
Labels: duplicate, feature request

**Comment by hbeni** [comment] 2023-09-14 05:39
Not exactly a duplicate - in #1235 it is about a omnidirectional speaker system.
Here, specifically:
> if possible, more directed (so the amplification only works in some kind of sound cone in the viewed direction).
