### ISSUE TITLE
(sys_core) script error

### ISSUE THREAD

**Issue by Cuel** [IDI-Systems/acre2#464] opened 2017-12-05 21:36 UTC
**Arma 3 Version:** 1.78
**CBA Version:** 3.5.0
**ACRE2 Version:** v2.5.1.980

**Mods:**
```
- CBA_A3
- acre2
```

**Description:**
```
22:26:10 Error in expression <llBack = acre_sys_core_threadedExtCalls select _id;
if ((if (isNil {_callBack}) >
22:26:10   Error position: <select _id;
if ((if (isNil {_callBack}) >
22:26:10   Error Zero divisor
22:26:10 File idi\acre\addons\sys_core\XEH_preInit.sqf, line 106
```

**Steps to reproduce:**
> I imagine that would happen with older versions as well although quite rare. By the looks of it's collecting results (async operation) from the acre dll but the array holding the callback functions is emptied by exiting the mission.

**Where did the issue occur?**
- client on Dedicated

**Comment by jonpas** [comment] 2018-11-29 11:52
Closing as we can't reproduce. Reopen if it reappears.

**Closed as completed by jonpas** 2018-11-29 11:52 UTC
Labels: bug, can't reproduce

**Comment by Cuel** [comment] 2018-11-29 11:54
Leaving a note: it's a rare error that happened on mission end
