### ISSUE TITLE
Radios are very unreliable concerning incoming transmissions

### ISSUE THREAD

**Issue by BlackAlpha** [IDI-Systems/acre2#264] opened 2017-03-18 01:01 UTC
**Arma 3 Version:** `1.68.140908` (stable)
**CBA Version:** `3.2.1.1702272` (stable)
**ACRE2 Version:** `2.4.0.942` (stable)

**Mods:**
- CBA_A3
- acre2

**Description:**
Radios randomly don't receive _some_ transmissions, even when the conditions don't change between the incoming transmissions. If you repeat the transmissions under the same conditions, then again it will randomly drop some of them. You do hear the radio clicks but not the actual transmission. The annoying part is that often this bug happens under perfect conditions where you clearly should be receiving the transmission.

The radios always work perfectly at the start, but it seems that something screws them up later down the line. This seems to be related to people traveling around the map. Therefore, it might also be related to the map terrain or buildings. But we haven't managed to pinpoint what the exact cause is.

During actual missions (containing many players) the bug is easily recognized when there's a group of people standing close to each other, and some of them receive a transmission while others don't.

Sometimes, you end up with a situation where two people are standing on the salt flats on Altis, close to each other (but far enough apart to be able to hear each other's transmissions), but they don't hear each other's radio transmissions. That's a sign that something is going horribly wrong with ACRE.

We found this bug back in October and we just did another (long) test with the latest ACRE version but the bug is still there. Unfortunately, in my community we had to rollback to ACRE version **2.1.0.811**. That's the last version where the radio worked normally. Maybe that can give you an idea what could be causing this bug.

Here's a video on an older ACRE version that shows the bug and how to reproduce it:
https://youtu.be/d7pOjGgNG7Q?t=13m15s

Here's one that shows the bug happening on the salt flats:
https://youtu.be/fNgW0f1HgpA?t=2m45s

**Steps to reproduce:**
We haven't found a scientific way to reproduce the bug. It seems to happen a lot by chance. Reproducing the bug can be a bit tedious because sometimes it happens fairly quickly (a minute into the mission), while other times it can take up to half an hour. I've had cases where the bug happened in hilly areas and not on the salt flats, but also vice versa! We've done tests with long and short transmissions but it happens with both. We've done tests with the terrain interference and antenna direction settings, but the bug happens with all settings we tried.

Anyway, here's how we pretty much always (eventually) manage to run into the bug.

- Create a new mission on Altis in the editor, add two playable infantry slots, give them a 148 radio each, and an empty helicopter.

- Start this mission on a dedicated server. Get in the helicopter, then travel to a random area on the map.

- Once landed, move about 500 meters away from each other. Try to keep line of sight to each other to make sure there's nothing blocking the signal. Also, I suspect that if you are within proximity of hills and/or buildings, you can increase the likelihood of running into this bug.

- Every time you stop to do a test, make each person do 10 short transmissions where you count to 10 (like you see people do in the videos I linked above), so that the other person knows when one of the transmissions has bugged out.

- The bug will probably not appear at first. So, get in the helo and travel to another area of the map, then repeat the above steps. Keep doing that until the bug appears, usually it happens after about 20 or so minutes of testing.

- Eventually, someone will not hear one (or more) of the numbers that are being transmitted. When that happens, don't move, then repeat the test a few times. If it keeps randomly dropping some transmissions, you've found the bug.

**Where did the issue occur?**
- Dedicated Server

**Placed Modules:**
- None

**RPT log file:**
https://gist.github.com/BlackAlpha/bb339647f82e15448afd520635e1d76d

**Comment by Soldia1138** [comment] 2017-03-18 05:36
Please change your difficulty settings to a lower terrainloss (e.g. 0.5) and/or ignore antenna direction. 
Documentation on Radio Loss:
http://acre2.idi-systems.com/wiki/user/radio-signal-loss

To have a better understanding of signal strength and its behavior, you can also activate the signal hint (`acre_sys_signal_showsignalhint = true` executed either locally or globally). 

In the end you can always put a custom signal loss model into place. http://acre2.idi-systems.com/wiki/frameworks/custom-signal-processing

**Comment by BlackAlpha** [comment] 2017-03-18 08:59
Tried that. Those settings didn't seem to affect the bug.

About the videos in particular. I wasn't there, so I'm not 100% sure what settings were used in the videos. But we don't change the ACRE settings, so whatever the default settings were back then is what was used in the videos, which I'm guessing is 0.5 terrain loss and antenna direction enabled.

Will do another test with the hint. Hopefully it will give us a hint on what's going on.

**Comment by Fourjays** [comment] 2017-03-18 11:53
Our group may also be noticing this issue, although I'm still trying to gather reliable information on it. We've found things considerably better since disabling antenna direction and overall it seems to occur far more frequently with the PRC343 than any other radio (the 148/152/117 are pretty reliable for us).

My only theory so far is that the "too close to receive" element of the simulation may be a bit inconsistent, or that there is a "lag" in when the calculations for when LOS are updating, but as I said I'm still trying to gather solid data on it.

We are running with terrain coefficient 0.8 and ignore antenna direction enabled.

**Comment by BlackAlpha** [comment] 2017-03-18 12:15
I made some progress! At least, I seem to have found a way to circumvent the bug, so my community can stay on ACRE. I also found some patterns that can hopefully help in fixing this issue.

Testing conditions:
- Person A halfway up a hill.
- Person B 500 meters down the hill.
- Both have clear line of sight on each other and there are no obstacles in the way.
- Note that we teleported to this hill (using setPos) - we teleported a couple of kilometers from our spawn point.

The bug happens with the default ACRE settings - some transmissions randomly don't get received. By turning off "Terrain Loss Coefficient" entirely (setting it to 0), we fixed the issue. If we use a setting higher than 0, the issue appears. Additionally, changing the antenna and model interference setting made no difference for us.

I turned on "acre_sys_signal_showSignalHint = true;". Transmissions that get randomly dropped get a percentage number of 0%. So, some transmissions get through and they get a high percentage, like 85%. But some transmissions don't get through, they get 0%.

There's also a pattern in the RPT log, notice how the 992 numbers don't appear for the transmissions that get dropped:
https://gist.github.com/BlackAlpha/b0245216c2e4d60ceb09c872b1a498f8

Hope this helps to fix the issue.

**Comment by Soldia1138** [comment] 2017-03-18 13:03
Thank you for testing. There are some things here we need to consider:

The signal calculation depends on the map height data. From this data all peaks are extracted and saved (in the extension part). To improve performance, the nearby peaks are checked on transmission and added to an array only valid for that mission. So after a while a more and more peaks are known and can be used for calculation. However the area where these peaks are gathered depends on radio characteristics. So there is a Chance that area is too small. Especially if you teleported to that area. 

The other thing is caching. We cache last signal calculation values for better performance. There may be indeed a link between the posted log data and a faulty caching. 

Maybe this is related to #258. 

I will check myself this evening.

**Comment by BlackAlpha** [comment] 2017-03-20 17:45
The issue is still  there even with terrain loss disabled.

Testing conditions:
- Person A on the northern edge of the big runway on Tanoa.
- Person B on the southern edge of the big runway on Tanoa.
- Each person has a 343 and 148 radio.

Sometimes the radios work, sometimes they don't. If they both walk to the middle of the runway, then walk back to where they started, the radios then seem to work properly.

**Comment by TheMagnetar** [comment] 2017-04-10 22:14
I wonder if this is fixed in the latest dev-build after fixing  #294...

**Comment by warzen** [comment] 2017-04-19 22:20
We had the same issue two times last week using 2.4.1.947 on Dariyah map.

**Comment by Rekkless88** [comment] 2017-08-11 14:19
If anyone wants to see this happening in action, here is a recording from last weeks mission. This bug seems to rare. But when it happens it makes for very difficult gameplay. 

In the video you can see me trying to get into contact with Reaper (our cas support) we have a direct line of sight with terrain interferance only set to 60% and both myself (APLHA Lead) and the Pilot and Co-Pilot of Reaper are running a PRC117. 

Myself and all other squads including Zeus can hear Reaper, but neither the pilot or copilot of reaper can anyone else.

I all honesty I can't remember a time when we have had this bug with any radio other than the 117.

https://youtu.be/-EjuidN20Yg?t=1h33m28s

**Comment by brainslush** [comment] 2017-08-12 09:42
What frequency were you using? We had this issue in the early days but after I spent some time finding and setting better frequencies this issue almost never reappeared .

**Comment by MaHuJa** [comment] 2017-08-14 20:45
The issue as reported has happened with every radio.
At 300m, in the saltflats - definitely has line of sight - you'd expect the radios to work regardless of frequency, right? But no such luck unless that's where we started the mission. Or moved there slowly enough, with a bit of luck. (The last known good version was .811 I think, and 64-bit arma3 can't use that.)

The key to reproducing is to either move people very rapidly (setpos across the map) or (somewhat less reliably) spawn them separately and move them to LOS.

**Comment by Sparfell** [comment] 2017-08-15 21:35
We are still experiencing the issue too. It's quite rare but very noticeable when it happens. Last time, I asked everybody to restart teamspeak while the game was still running and it seems it fixed the issue for the rest of the mission. I'll try again next time in order to see if it's a reliable workaround.

**Comment by jonpas** [comment] 2017-08-15 21:49
@jp Maybe #380 fixed this?

**Comment by Sparfell** [comment] 2017-08-16 15:11
@jonpas On my side, antenna direction is ignored.

**Comment by MaHuJa** [comment] 2017-09-19 20:32
I and @BlackAlpha just tested with 2.5.0 and this bug is still there. One difference though is that we are now unable to reproduce it with terrain loss coef set to 0.

**Comment by jonpas** [comment] 2017-09-19 20:35
@MaHuJa Do you mean when manually changing terrain loss coef to 0? You could reproduce by doing that before?

**Comment by MaHuJa** [comment] 2017-09-19 20:40
We set a server setting for terrain loss coef to 0, and the bug apparently vanished - or we got very lucky. In the previous version we tested (I believe we didn't test since 2.4.0 in the OP) this still left the symptoms (random transmissions dropping) present.

**Comment by jonpas** [comment] 2017-09-19 20:47
> this still left the symptoms (random transmissions dropping) present.

That was probably the antenna direction bug, which was fixed in 2.5.0.

**Comment by MaHuJa** [comment] 2017-09-19 20:58
>the antenna direction bug
1. Turning off antenna direction in the addon options did not affect the bug in the previous tested version, nor did it seem to affect it today.
2. That bug sounded to me like, if you're not moving, it should either affect all or none of the transmissions. We typically lose 5-20% of transmissions depending on 'luck' (factors we are unable to determine).

**Comment by BlackAlpha** [comment] 2017-09-19 21:08
About the tests done today, the issue we (Mahuja and myself) had was that random messages don't get through on the radio. When this happens you can hear the radio effect sounds, but the voice is not coming through. It seems to be related to the terrain loss coefficent setting, as turning that one off made the bug go away. We experienced this issue with both the 343 and 148 radios (we mostly tested with the 343, we tested with the 148 very briefly).

We used the following scripting command to enable an ACRE debug message: acre_sys_signal_showsignalhint = true
When the bug occurs it shows the percentage number as 0%.

Steps to reproduce...

Modset: Latest version of CBA, ACRE and MCC (for debugging purposes).
Mission: https://www.dropbox.com/s/tptklj9rs5bprdl/acretest1.Tanoa.pbo?dl=0
ACRE settings: Default

1. Load up the mission on a dedicated server.
2. Teleport both players to another airfield. Teleport each player to the opposite ends of the runway.
3. Make each player count from 0 to 20 on the radio, with each number being its own transmission (press and release radio key between each number).
4. If the bug doesn't appear, teleport to a different airfield and repeat the above steps. Eventually you run into it.

We did quite a bit of testing and we always ran into the bug when we had terrain coefficient set to 0.5. Turning off antenna direction and turning off model interference had no effect. When we turned off terrain loss coefficient, we couldn't reproduce the bug after testing on 4 different airfields. When we had terrain loss coefficient enabled, we ran into the bug quite often, usually at the first or second airfield.

**Comment by jonpas** [comment] 2017-09-19 21:22
> Modset: Latest version of CBA, ACRE and MCC (for debugging purposes).

I assume it also happened with only CBA + ACRE2? MCC is kind of known to interfere with things in various weird ways.

**Comment by BlackAlpha** [comment] 2017-09-19 21:25
Yes.

**Comment by MaHuJa** [comment] 2018-01-22 14:59
I'd suggest changing the issue title to "Intermittent transmission drops away from initial area". The current title is too broad and people seem to confuse it with other situations they have.

I did some digging into the plugin code and found nothing that would explain the intermittent behavior. I'm thinking to look into the sqf code next. In particular, what happens when the plugin is late in providing a signal strength?

**Comment by Soldia1138** [comment] 2018-11-29 08:06
What is the current status on this? There are no major issues regarding this in our community. What about others?

**Comment by jonpas** [comment] 2018-11-29 11:50
No issues here either.

**Comment by CPTMiller** [comment] 2018-12-12 12:36
This happens still at our community. Same bug, same procedures.

**Comment by Fourjays** [comment] 2018-12-12 18:33
Our group of testers last tried it around September and were still encountering the issue. We give it a go whenever we run out of other things to test, trying to narrow it down, but have yet to get it to a point where we can definitively report what it is or how to reliably reproduce it.

What we've found so far is that with the terrain coefficient set to 0, there's no issue at all (we host ops daily with it set like this and radio transmissions are 100% reliable). If anyone has the issue with a terrain coefficient of 0, then we may be discussing two different issues entirely.

However, if the terrain coefficient is any value above that, then radio transmissions will be dropped, seemingly at random. The most reliable case to reproduce it we found (but it still isn't 100%) is around rocky coastlines on Tanoa. An example from memory:
- Person 1 standing on the beach on Tanoa with a 343.
- Person 2 standing <50m away on a rock with a 343.
- Person 3 standing <100m away on a hillside beyond the rock with a 343.
- All 3 have line of sight with each other, yet comms would randomly get dropped.

It has always felt really situation specific. At the start of the year we ran it in an op, believing it to be fixed. We went through an hour of an operation without issue. Then we were crossing a patch of relatively flat desert (was near an old fort on Isla Duala or Dingor if I remember right) and were unable to communicate with people we could see ~100m away.

It also seems a _little_ easier to reproduce in an operation with 30+ people than in a test session with 2-5 people. There's been a few times that we've run tests and everything has seemed fine, then we turn it on for an operation and _someone_ encounters it. That could indicate some kind of network/performance issue, or could just be because more people means more chances of running into the issue.

My own personal guess (based on my observations) is that there is something not quite right in how specific terrain/objects are being interpreted by ACRE. For example, could it be seeing "Rock_X" as twice the size it actually is, or a long low hill as a big hill? The reason I think this is I've always noticed it when we're on ground that has rock/tree/bush clutter but very little terrain variation.

No idea if any of this is helpful or not. Would like to give you more concrete information, but we've just been unable to narrow it down further than this in the last year or more of trying to do so.

**Comment by Soldia1138** [comment] 2020-03-10 20:17
Any news on this? Would be interesting if this is the same with the different signal calculation methods.
Will close end of march if there aren't any new reports on this

**Comment by Fourjays** [comment] 2020-03-13 10:53
@Soldia1138 Since the update that included the "Simple LOS" signal mode we have been running with a terrain coefficient of 0.5 and had zero cases of unexplained communication loss. I can't speak to how other modes behave as we haven't tried them at all. "Simple LOS" delivers exactly what we have always been looking for from ACRE.

Here's our working settings in case they are helpful to anyone still having issues:
```
acre_sys_core_automaticAntennaDirection = true;
acre_sys_core_fullDuplex = true;
acre_sys_core_ignoreAntennaDirection = false;
acre_sys_core_interference = false;
acre_sys_core_revealToAI = 1;
acre_sys_core_terrainLoss = 0.5;
acre_sys_signal_signalModel = 1;
```

**Comment by Soldia1138** [comment] 2020-04-17 10:00
If it's still an issue (after next release), feel free to re-open

**Closed as completed by Soldia1138** 2020-04-17 10:00 UTC
Labels: bug
