### ISSUE TITLE
ACRE2 compatibility issues with linux server

### ISSUE THREAD

**Issue by TFWIsaac** [IDI-Systems/acre2#407] opened 2017-09-20 21:35 UTC
**Arma 3 Version:** stable
**CBA Version:** `3.4.11`
**ACRE2 Version:** `2.5.0.968` stable 

**Mods:**
```
- CBA_A3
- acre2
- Ace3
- acex
- advanced train simulator
- Ares Mod- Achilles Expansion
- BW_Kleiderkammer
- bwa3
- bwa3_ace
- Eden Objects
- Extended Fortifications Mod
- FM_China
- FM_Gold
- Identizee_V2
- JS_JC_FA18
- NIArms
- Project OPFOR
- RDS_Civ
- RHSAFRF
- RHSGREF
- RHSUSAF
- and a lot of own created mods
```

**Description:**
Actually we have the issues, that if player (we call this player in this example "A") JIP a mission (JIP = Join in Progress) that this player A can't hear the other player if they transmitting on a radio. At the other side, if player A transmitted on a radio, the other player can hear them. Now if another player (now player B) JIP in the mission, then only player A can hear them by transmissions. And the other way around player B can only hear player A. And so...

**Where did the issue occur?**
- Dedicated Server (Linux)

**ACRE2 Settings:**
In our init.sqf we have the following acre2 settings: [Pastebin Link](https://pastebin.com/bZb37NzD)

**Placed Modules:**
- None

**Our Result:**
We have the guess, that ACRE2 have some compatibility issues with Linux Server. We have reproduced this, with the same Modpack at a local hosted Windows OS. In this case we have non issues.  So we figure out, that there must be some issues with compatibility on Linux OS.

**Comment by jonpas** [comment] 2017-09-20 21:53
You shouldn't be using those API functions from line 6 to 10, they are deprecated and will be removed in the future. Use CBA Settings.

Unless you can reproduce it with ONLY latest CBA + ACRE2, we can't do much to help. Any one of those mods could be causing issues. Or even a badly designed mission.

Not able to reproduce on Windows could just be a matter of circumstances. There is nothing we even do on the OS level, only clients run the extension.

To clarify, when you say "can't hear other player if they transmit on a radio", you mean if they start transmitting after they join, not start before they join and just continue, correct?

**Comment by Soldia1138** [comment] 2017-09-22 20:57
This sounds like your presets are not set correctly.

As a reminder:
Presets __MUST__ be the same on __ALL__ machines.
If I look on your pastebin, this is not the case for the dedicated server. (Which is one reason it works on your __local__ hosted server)

Plus you need to be sure that presets are set before the gear assignment is handled. Cause the radios will fetch the presets the moment they are assigned (when they get an unique ID).

**Comment by TheMagnetar** [comment] 2017-09-23 09:05
I have always been using a Linux Dedicated Server and I cannot reproduce the issue you describe either with CBA + ACRE2 (+ACE3). Also throwing RHS and BW into the mix did not cause it. As Soldia pointed out, out of sync presets may cause the issue.

**Comment by TFWIsaac** [comment] 2017-09-23 16:43
Okay, we will check out our Presets in the next days, we also want to test only CBA+ACRE2 on the server.

**Comment by jonpas** [comment] 2017-10-13 16:35
Any further information?

**Comment by TheMagnetar** [comment] 2017-11-22 08:44
Closing due to lack of updates. Also issue could not be reproduced.

**Closed as completed by TheMagnetar** 2017-11-22 08:44 UTC
Labels: need more info
