### ISSUE TITLE
11-second interval microstutter in singleplayer

### ISSUE THREAD

**Issue by dslyecxi** [IDI-Systems/acre2#1007] opened 2020-08-10 15:59 UTC
**Mods:**
- **Arma 3:** `["Arma 3","Arma3",198,146373,"Stable",true,"Windows","x64"]` 
- **CBA:** `3.15.1` 
- **ACRE2:** `2.7.4.1030` 

**Description:**
When running ACRE2 in singleplayer, every 11 seconds a microstutter will occur (a hitch that repeats frames - for me, typically 2-3 frames when running between 30-60fps). This goes away when ACRE2 is not loaded. This does not occur in multiplayer. It's a very subtle thing until you notice the pattern and presentation of the microstutter, then it's pretty easy to see. 

**Steps to reproduce:**
- Load Altis, place down a character for yourself on the ground, then a helicopter that's flying that is moving at a limited speed, give it a long oval-shaped series of looping waypoints. 
- Preview the mission, go into camera mode, move to the area the helicopter is flying around
- Move the camera smoothly to track the helicopter. Every 11 seconds you will see it stutter (which basically looks like it jumps ahead a few meters). It's not the helo itself that's stuttering, that's just the clearest way to see the issue. 

**Expected behavior:**
Whatever check is happening in this context shouldn't happen, and the microstutter should not be present. 

**Where did the issue occur?**
-  Singleplayer

**Comment by Soldia1138** [comment] 2020-08-10 16:24
That’s the long frame caused by the Master ID Tracker. This usually runs on the server. 

Most obvious solution would be to deactivate ACRE completely in SP or only allow for a bare Minimum of Features.

**Comment by PabstMirror** [comment] 2020-08-10 16:28
one oddity I've found is `(allMissionObjects "WeaponHolder")` is **much** more expensive on clients compared to a dedicated server

**Comment by jonpas** [comment] 2023-04-10 14:22
@JonBons Is #1234 related to this, or is this still a separate issue?

**Comment by jonpas** [comment] 2023-09-14 00:16
Closing as potentially fixed by #1234. If it's still an issue in v2.11 or higher, leave a comment and we will re-open.

**Closed as not planned by jonpas** 2023-09-14 00:16 UTC
Labels: bug

**Comment by PabstMirror** [comment] 2023-09-14 00:33
saw this recently, haven't tested
2.14.150962 new PROFILING branch
> Script commands allMissionObjects/nearestObjects/nearObjects/nearSupplies/nearRoads/nearestTerrainObjects are multithreaded
